name: test-linter-check

on: push

jobs:
  review:
    runs-on: ubuntu-latest

    steps:
      # Check-out repository under GitHub workspace
      # https://github.com/actions/checkout
      - uses: actions/checkout@v3
      # Configures the node version used on GitHub-hosted runners
      # https://github.com/actions/setup-node
      - uses: actions/setup-node@v3

      - run: make install  
      
      - name: run tests
        run: make test
      
      - name: run lint
        run: make lint