name: test-linter-check

on: push

jobs:
  review:
    runs-on: ubuntu-latest

    steps:
      # Check-out repository under GitHub workspace
      # https://github.com/actions/checkout
      - uses: actions/checkout@v3
      # Configures the node version used on GitHub-hosted runners
      # https://github.com/actions/setup-node
      - uses: actions/setup-node@v3

      - run: make install  
      
      - name: run tests
        run: make test
      
      - name: run lint
        run: make lint

      - name: Test & publish code coverage
        # Publish code coverage on Code Climate
        # https://github.com/paambaati/codeclimate-action
        uses: paambaati/codeclimate-action@v3.0.0
        # Add Code Climate secret key
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageCommand: make test-coverage
          debug: true